[package]
name = "tokio"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
redis = { version = "0.29.0", features = ["tokio-comp"] }
clap = { version = "4.5.30", features = ["derive"] }
r2d2 = "0.8.10"
log = "0.4.26"
simple_logger = "5.0.0"
